In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('data/CarPrice_Assignment.csv')

In [4]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    str
 3   fueltype          205 non-null    str
 4   aspiration        205 non-null    str
 5   doornumber        205 non-null    str
 6   carbody           205 non-null    str
 7   drivewheel        205 non-null    str
 8   enginelocation    205 non-null    str
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    str
 15  cylindernumber    205 non-null    str
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    str
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), str(10)
memory usage: 51.8 KB

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder

In [8]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [15]:
df['CarName'].unique()

<ArrowStringArray>
[      'alfa-romero giulia',      'alfa-romero stelvio',
 'alfa-romero Quadrifoglio',              'audi 100 ls',
               'audi 100ls',                 'audi fox',
                'audi 5000',                'audi 4000',
      'audi 5000s (diesel)',                 'bmw 320i',
 ...
                'vw rabbit',        'volkswagen rabbit',
 'volkswagen rabbit custom',          'volvo 145e (sw)',
              'volvo 144ea',              'volvo 244dl',
                'volvo 245',              'volvo 264gl',
             'volvo diesel',                'volvo 246']
Length: 147, dtype: str

In [19]:
data = {}
for idx, name in enumerate(df['CarName'].unique(), 1):
    # print(idx, name)
    data[name] = idx

In [22]:
df['CarName'] = df['CarName'].map(data)

In [23]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,1,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,2,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,3,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,4,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,5,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,141,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,142,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,143,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,147,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,145,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [27]:
df['doornumber'] = df['doornumber'].map({'two': 2, 'four':4})

In [28]:
df['cylindernumber'].unique()

<ArrowStringArray>
['four', 'six', 'five', 'three', 'twelve', 'two', 'eight']
Length: 7, dtype: str

In [30]:
df['cylindernumber'] = df['cylindernumber'].map({'four':4, 'six':6, 'five':5, 'three': 3, 'twelve':12, 'two': 2, 'eight': 8})

In [33]:
df.nunique()

car_ID              205
symboling             6
CarName             147
fueltype              2
aspiration            2
doornumber            2
carbody               5
drivewheel            3
enginelocation        2
wheelbase            53
carlength            75
carwidth             44
carheight            49
curbweight          171
enginetype            7
cylindernumber        7
enginesize           44
fuelsystem            8
boreratio            38
stroke               37
compressionratio     32
horsepower           59
peakrpm              23
citympg              29
highwaympg           30
price               189
dtype: int64

In [36]:
from sklearn.compose import ColumnTransformer

In [38]:
df.select_dtypes('string').columns

Index(['fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginelocation',
       'enginetype', 'fuelsystem'],
      dtype='str')

In [43]:
col = ColumnTransformer(
    transformers=[('onehot', OneHotEncoder(drop='first', sparse_output=False), df.select_dtypes('string').columns),
                 ('scale', StandardScaler(), df.select_dtypes('number').columns)],
    remainder='passthrough'
)

In [46]:
arr = col.fit_transform(df)

In [45]:
col.get_feature_names_out()

array(['onehot__fueltype_gas', 'onehot__aspiration_turbo',
       'onehot__carbody_hardtop', 'onehot__carbody_hatchback',
       'onehot__carbody_sedan', 'onehot__carbody_wagon',
       'onehot__drivewheel_fwd', 'onehot__drivewheel_rwd',
       'onehot__enginelocation_rear', 'onehot__enginetype_dohcv',
       'onehot__enginetype_l', 'onehot__enginetype_ohc',
       'onehot__enginetype_ohcf', 'onehot__enginetype_ohcv',
       'onehot__enginetype_rotor', 'onehot__fuelsystem_2bbl',
       'onehot__fuelsystem_4bbl', 'onehot__fuelsystem_idi',
       'onehot__fuelsystem_mfi', 'onehot__fuelsystem_mpfi',
       'onehot__fuelsystem_spdi', 'onehot__fuelsystem_spfi',
       'scale__car_ID', 'scale__symboling', 'scale__CarName',
       'scale__doornumber', 'scale__wheelbase', 'scale__carlength',
       'scale__carwidth', 'scale__carheight', 'scale__curbweight',
       'scale__cylindernumber', 'scale__enginesize', 'scale__boreratio',
       'scale__stroke', 'scale__compressionratio', 'scale__horsepower',
       'scale__peakrpm', 'scale__citympg', 'scale__highwaympg',
       'scale__price'], dtype=object)

In [53]:
arr[:, :-1]

array([[ 1.        ,  0.        ,  0.        , ..., -0.26296022,
        -0.64655303, -0.54605874],
       [ 1.        ,  0.        ,  0.        , ..., -0.26296022,
        -0.64655303, -0.54605874],
       [ 1.        ,  0.        ,  0.        , ..., -0.26296022,
        -0.95301169, -0.69162706],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.78785546,
        -1.10624102, -1.12833203],
       [ 0.        ,  1.        ,  0.        , ..., -0.68328649,
         0.11959362, -0.54605874],
       [ 1.        ,  1.        ,  0.        , ...,  0.57769233,
        -0.95301169, -0.83719538]], shape=(205, 40))

In [51]:
arr.shape

(205, 41)

In [54]:
X = arr[:, :-1]
y = arr[:, -1]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
X_train.shape

(164, 40)

In [57]:
import numpy as np

In [67]:
class SimpleLinearReg:
    def __init__(self):
        self.m = 0
        self.b = 0
    def fit(self, x, y):
        x_mean  = np.mean(x)
        y_mean  = np.mean(y)
        numerator = np.sum((x - x_mean) * (y-y_mean))
        denominator  = np.sum((x-x_mean)**2)
        self.m = numerator / denominator
        self.b = y_mean - (self.m * x_mean)
        return self.m, self.b

    def predict(self, x_test):
        y = self.m * x_test + self.b
        return y

In [68]:
obj = SimpleLinearReg()
obj.fit(X, y.reshape(-1,1))

(np.float64(0.19701784600334105), np.float64(-0.02419475255187355))

In [69]:
obj.predict(X_test)

array([[ 0.17282309, -0.02419475, -0.02419475, ...,  0.08962095,
        -0.3025218 , -0.27517586],
       [ 0.17282309,  0.17282309, -0.02419475, ...,  0.13102683,
        -0.3025218 , -0.27517586],
       [ 0.17282309, -0.02419475, -0.02419475, ...,  0.00680917,
         0.02955624,  0.06897883],
       ...,
       [ 0.17282309, -0.02419475, -0.02419475, ...,  0.08962095,
         0.36163428,  0.32709485],
       [ 0.17282309,  0.17282309, -0.02419475, ..., -0.07600261,
        -0.21195506, -0.21781674],
       [ 0.17282309, -0.02419475, -0.02419475, ..., -0.15881438,
         0.05974515,  0.01161972]], shape=(41, 40))

In [78]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [71]:
model = LinearRegression()

In [72]:
model.fit(X_train, y_train)

LinearRegression()

In [73]:
model.predict(X_test)

array([ 1.77868367,  0.70584364, -0.40712328, -0.09065776,  1.90605693,
       -0.98656353, -0.71112622, -0.84783929, -0.5810327 , -0.68889117,
        0.18086482, -0.81139664,  0.65495336, -0.57265538,  3.59830077,
       -0.83455838, -2.45676035,  0.03996138, -0.3815008 , -0.37976092,
       -0.12645886,  0.56504617, -0.8767447 , -1.13156569, -0.72388318,
        1.73227906, -0.12424853,  0.38794057, -1.11668353,  0.48933754,
        1.95208799, -0.96857991, -0.91505318,  1.11017613, -0.73405117,
        1.76698494,  0.00892493, -0.0666834 , -0.75822313,  0.08617847,
       -0.84761354])

In [76]:
lasso = Lasso(alpha=0.1)
lasso.fit(X_train, y_train)
y_pred=lasso.predict(X_test)

In [74]:
from sklearn.metrics import r2_score
r2_score(y_test, model.predict(X_test))

0.8484396174993535

In [77]:
r2_score(y_test, y_pred)

0.7998048919649005

In [79]:
lasso = Ridge(alpha=0.01)
lasso.fit(X_train, y_train)
y_pred=lasso.predict(X_test)

In [80]:
r2_score(y_test, y_pred)

0.8492297994293645

In [ ]:
skle