<a href="https://colab.research.google.com/github/UdayMalviya/DataScience_Morning/blob/master/pandas/pandas_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### introduction to pandas, dataframe and series and indexing

In [ ]:
import pandas as pd

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])

In [ ]:
s = pd.Series(arr, dtype=np.int32, name='A')

In [ ]:
s

0    1
1    2
2    3
Name: A, dtype: int32

In [ ]:
s + s

0    2
1    4
2    6
Name: A, dtype: int32

In [ ]:
s.name

'A'

In [ ]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
s.values

array([1, 2, 3], dtype=int32)

In [ ]:
df = pd.DataFrame({'A': [1,2,3,4,5], 'B': [10, 20, 30, 40, 50]})

In [ ]:
df

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [ ]:
s.shape, df.shape

((3,), (5, 2))

In [ ]:
s[0]

np.int64(1)

In [ ]:
type(df['A'])

pandas.core.series.Series

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [ ]:
df['C'] = [4,5,6,7,8]

In [ ]:
df

   A   B  C
0  1  10  4
1  2  20  5
2  3  30  6
3  4  40  7
4  5  50  8

In [ ]:
s = pd.Series(np.arange(1, 1001), name='col1')

In [ ]:
s  s

0         2
1         4
2         6
3         8
4        10
       ...
995    1992
996    1994
997    1996
998    1998
999    2000
Name: col1, Length: 1000, dtype: int64

In [ ]:
df * s

,A,B,C,0,1,2,3,4,5,6,...,990,991,992,993,994,995,996,997,998,999
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
%ls

sample_data/

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

### how to see top `N` rows

In [ ]:
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

### bottom `N` rows

In [ ]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# how to see the sample of dataframe
df.sample(20)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
11548,-121.27,38.13,35.0,2607.0,685.0,2016.0,618.0,1.7500,82900.0
9040,-118.97,35.38,42.0,1185.0,358.0,1038.0,299.0,0.9951,48000.0
12635,-121.73,36.86,28.0,827.0,178.0,703.0,144.0,4.4271,175700.0
10386,-120.19,36.61,29.0,1479.0,338.0,1408.0,322.0,2.2930,57200.0
15313,-122.28,37.55,17.0,4199.0,629.0,2020.0,630.0,6.1228,375700.0
4353,-118.02,34.08,29.0,2741.0,667.0,2449.0,677.0,3.6944,175200.0
14296,-122.09,37.39,34.0,1508.0,483.0,774.0,443.0,2.7279,365600.0
8318,-118.46,34.42,25.0,2988.0,525.0,1884.0,513.0,4.7007,169500.0
5626,-118.18,34.05,38.0,3272.0,731.0,3299.0,726.0,2.8295,126500.0
3504,-117.90,33.85,35.0,1756.0,328.0,1026.0,332.0,3.6000,193500.0
15158,-122.26,37.54,5.0,1649.0,388.0,779.0,376.0,6.9635,417300.0
8892,-118.82,35.23,31.0,2358.0,580.0,2302.0,574.0,1.9688,53900.0
13129,-121.88,37.24,24.0,4420.0,996.0,2981.0,975.0,3.5060,226400.0
1431,-117.18,32.69,37.0,3112.0,716.0,1304.0,674.0,3.2121,320800.0
12405,-121.56,39.01,22.0,1891.0,340.0,1023.0,296.0,2.7303,99100.0
3675,-117.92,33.74,13.0,4620.0,1265.0,3385.0,1109.0,3.1773,186500.0
12583,-121.68,39.11,19.0,1366.0,220.0,596.0,203.0,4.0625,141700.0
15710,-122.39,37.60,36.0,1770.0,499.0,1225.0,459.0,2.5600,273100.0
7185,-118.33,34.10,48.0,1116.0,524.0,1610.0,483.0,1.6250,237500.0
12910,-121.83,37.29,20.0,1649.0,408.0,1729.0,362.0,3.3833,115200.0

In [ ]:
df.describe() # statistical summary

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB